name: Build V2Ray iOS (a-Shell)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for iOS (Mach-O ARM64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Download v2ray-core
        run: |
          git clone --depth=1 https://github.com/XTLS/Xray-core.git v2ray-core

      - name: Build binary
        run: |
          cd v2ray-core
          go mod tidy
          cd ..
          go build -o v2ray-ios -ldflags="-s -w" ./main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: v2ray-ios
          path: v2ray-ios
